USE vapor;

SELECT 
  `members`.`active` AS `active_(members)`,
  `profiles`.`active` AS `active_(profiles)`,
  `users`.`active` AS `active_(users)`,
  `orders`.`active` AS `active`,
  `events`.`address` AS `address_(events)`,
  `orders`.`address` AS `address_(orders)`,
  `registration_audit`.`address` AS `address_(registration_audit)`,
  `membership_applications`.`address` AS `address`,
  `orders`.`address_2` AS `address_2`,
  `events`.`allow_one_day_purchases` AS `allow_one_day_purchases`,
  `transactions`.`amount` AS `amount`,
  `orders`.`amount_charged_back` AS `amount_charged_back_(orders)`,
  `order_products`.`amount_charged_back` AS `amount_charged_back`,
  `order_products`.`amount_per` AS `amount_per`,
  `orders`.`amount_refunded` AS `amount_refunded_(orders)`,
  `order_products`.`amount_refunded` AS `amount_refunded`,
  `profiles`.`anonymous` AS `anonymous`,
  `users`.`api_token` AS `api_token`,
  `membership_applications`.`application_type` AS `application_type`,
  `membership_applications`.`approval_status` AS `approval_status`,
  `events`.`athlete_guide_url` AS `athlete_guide_url`,
  `registration_audit_membership_application`.`audit_id` AS `audit_id`,
  `order_products`.`base_price` AS `base_price`,
  `registration_audit`.`billing_address` AS `billing_address`,
  `registration_audit`.`billing_city` AS `billing_city`,
  `registration_audit`.`billing_country` AS `billing_country`,
  `registration_audit`.`billing_email` AS `billing_email`,
  `registration_audit`.`billing_first_name` AS `billing_first_name`,
  `registration_audit`.`billing_last_name` AS `billing_last_name`,
  `registration_audit`.`billing_middle_name` AS `billing_middle_name`,
  `registration_audit`.`billing_phone` AS `billing_phone`,
  `registration_audit`.`billing_state` AS `billing_state`,
  `registration_audit`.`billing_zip` AS `billing_zip`,
  `transactions`.`captured` AS `captured`,
  `order_products`.`cart_description` AS `cart_description`,
  `order_products`.`cart_label` AS `cart_label`,
  `events`.`certified_race_director` AS `certified_race_director`,
  `events`.`city` AS `city_(events)`,
  `orders`.`city` AS `city_(orders)`,
  `registration_audit`.`city` AS `city_(registration_audit)`,
  `membership_applications`.`city` AS `city`,
  `users`.`claimed` AS `claimed`,
  SUBSTRING(`membership_applications`.`club_affiliations`, 1, 1024) AS `club_affiliations`,
  `membership_applications`.`confirmation_code` AS `confirmation_code`,
  `registration_audit`.`confirmation_number` AS `confirmation_number_(registration_audit)`,
  `orders`.`confirmation_number` AS `confirmation_number`,
  `events`.`country` AS `country_(events)`,
  `orders`.`country` AS `country_(orders)`,
  `registration_audit`.`country` AS `country_(registration_audit)`,
  `membership_applications`.`country` AS `country`,
  `events`.`country_code` AS `country_code`,
  `events`.`country_name` AS `country_name`,
  `events`.`created_at` AS `created_at_(events)`,
  `members`.`created_at` AS `created_at_(members)`,
  `membership_periods`.`created_at` AS `created_at_(membership_periods)`,
  `membership_types`.`created_at` AS `created_at_(membership_types)`,
  `order_products`.`created_at` AS `created_at_(order_products)`,
  `orders`.`created_at` AS `created_at_(orders)`,
  `profiles`.`created_at` AS `created_at_(profiles)`,
  `registration_audit`.`created_at` AS `created_at_(registration_audit)`,
  `registration_audit_membership_application`.`created_at` AS `created_at_(registration_audit_membership_application)`,
  `transactions`.`created_at` AS `created_at_(transactions)`,
  `users`.`created_at` AS `created_at_(users)`,
  `membership_applications`.`created_at` AS `created_at`,
  SUBSTRING(`orders`.`customer_note`, 1, 1024) AS `customer_note`,
  `transactions`.`date` AS `date`,
  `profiles`.`date_of_birth` AS `date_of_birth_(profiles)`,
  `registration_audit`.`date_of_birth` AS `date_of_birth_(registration_audit)`,
  `membership_applications`.`date_of_birth` AS `date_of_birth`,
  `profiles`.`deceased_recorded_on` AS `deceased_recorded_on`,
  `events`.`deleted_at` AS `deleted_at_(events)`,
  `members`.`deleted_at` AS `deleted_at_(members)`,
  `membership_periods`.`deleted_at` AS `deleted_at_(membership_periods)`,
  `membership_types`.`deleted_at` AS `deleted_at_(membership_types)`,
  `order_products`.`deleted_at` AS `deleted_at_(order_products)`,
  `orders`.`deleted_at` AS `deleted_at_(orders)`,
  `profiles`.`deleted_at` AS `deleted_at_(profiles)`,
  `registration_audit`.`deleted_at` AS `deleted_at_(registration_audit)`,
  `transactions`.`deleted_at` AS `deleted_at_(transactions)`,
  `users`.`deleted_at` AS `deleted_at_(users)`,
  `membership_applications`.`deleted_at` AS `deleted_at`,
  SUBSTRING(`membership_applications`.`denial_reason`, 1, 1024) AS `denial_reason`,
  SUBSTRING(`events`.`description`, 1, 1024) AS `description`,
  `orders`.`discount` AS `discount_(orders)`,
  `order_products`.`discount` AS `discount`,
  `orders`.`discount_code` AS `discount_code`,
  `events`.`distance` AS `distance`,
  `registration_audit_membership_application`.`distance_type_id` AS `distance_type_id_(registration_audit_membership_application)`,
  `membership_applications`.`distance_type_id` AS `distance_type_id`,
  `profiles`.`education_id` AS `education_id`,
  `orders`.`email` AS `email_(orders)`,
  `registration_audit`.`email` AS `email_(registration_audit)`,
  `users`.`email` AS `email_(users)`,
  `membership_applications`.`email` AS `email`,
  `users`.`email_verified_at` AS `email_verified_at`,
  `events`.`ends` AS `ends_(events)`,
  `membership_periods`.`ends` AS `ends`,
  `registration_audit`.`ethnicity` AS `ethnicity`,
  `profiles`.`ethnicity_id` AS `ethnicity_id`,
  `registration_audit`.`event_id` AS `event_id_(registration_audit)`,
  `membership_applications`.`event_id` AS `event_id`,
  `events`.`event_type_id` AS `event_type_id`,
  `events`.`event_website_url` AS `event_website_url`,
  `transactions`.`exported_at` AS `exported_at`,
  `membership_types`.`extension_type` AS `extension_type_(membership_types)`,
  `membership_applications`.`extension_type` AS `extension_type`,
  `events`.`facebook_url` AS `facebook_url`,
  `events`.`featured_at` AS `featured_at`,
  `orders`.`first_name` AS `first_name_(orders)`,
  `profiles`.`first_name` AS `first_name_(profiles)`,
  `registration_audit`.`first_name` AS `first_name_(registration_audit)`,
  `membership_applications`.`first_name` AS `first_name`,
  `registration_audit`.`gender` AS `gender_(registration_audit)`,
  `membership_applications`.`gender` AS `gender`,
  `profiles`.`gender_id` AS `gender_id`,
  `profiles`.`gender_opt_out` AS `gender_opt_out`,
  `orders`.`group_id` AS `group_id`,
  `orders`.`handling_charge` AS `handling_charge`,
  `orders`.`handling_tax` AS `handling_tax`,
  `events`.`id` AS `id_(events)`,
  `members`.`id` AS `id_(members)`,
  `membership_periods`.`id` AS `id_(membership_periods)`,
  `membership_types`.`id` AS `id_(membership_types)`,
  `order_products`.`id` AS `id_(order_products)`,
  `orders`.`id` AS `id_(orders)`,
  `profiles`.`id` AS `id_(profiles)`,
  `registration_audit`.`id` AS `id_(registration_audit)`,
  `registration_audit_membership_application`.`id` AS `id_(registration_audit_membership_application)`,
  `transactions`.`id` AS `id_(transactions)`,
  `users`.`id` AS `id_(users)`,
  `membership_applications`.`id` AS `id`,
  `orders`.`in_hand_date` AS `in_hand_date`,
  `profiles`.`income_id` AS `income_id`,
  `events`.`instagram_url` AS `instagram_url`,
  SUBSTRING(`orders`.`internal_note`, 1, 1024) AS `internal_note`,
  `users`.`invalid_email` AS `invalid_email`,
  SUBSTRING(`users`.`invalid_email_value`, 1, 1024) AS `invalid_email_value`,
  `registration_audit`.`invoice_product_id` AS `invoice_product_id`,
  `profiles`.`is_us_citizen` AS `is_us_citizen`,
  `orders`.`last_name` AS `last_name_(orders)`,
  `profiles`.`last_name` AS `last_name_(profiles)`,
  `registration_audit`.`last_name` AS `last_name_(registration_audit)`,
  `membership_applications`.`last_name` AS `last_name`,
  `events`.`last_season_event_id` AS `last_season_event_id`,
  `users`.`logged_in_at` AS `logged_in_at`,
  `members`.`longevity_status` AS `longevity_status`,
  `profiles`.`marketo_lead_id` AS `marketo_lead_id`,
  `profiles`.`marketo_lead_id_old` AS `marketo_lead_id_old`,
  `membership_periods`.`member_id` AS `member_id`,
  `members`.`member_number` AS `member_number_(members)`,
  `registration_audit`.`member_number` AS `member_number`,
  `members`.`memberable_id` AS `memberable_id`,
  `members`.`memberable_type` AS `memberable_type`,
  `registration_audit_membership_application`.`membership_application_id` AS `membership_application_id`,
  `membership_types`.`membership_card_template_id` AS `membership_card_template_id`,
  `membership_types`.`membership_licenses_type_id` AS `membership_licenses_type_id`,
  `registration_audit`.`membership_period_id` AS `membership_period_id_(registration_audit)`,
  `membership_applications`.`membership_period_id` AS `membership_period_id`,
  `membership_periods`.`membership_type_id` AS `membership_type_id_(membership_periods)`,
  `registration_audit_membership_application`.`membership_type_id` AS `membership_type_id_(registration_audit_membership_application)`,
  `membership_applications`.`membership_type_id` AS `membership_type_id`,
  SUBSTRING(`users`.`merge_info`, 1, 1024) AS `merge_info_(users)`,
  SUBSTRING(`profiles`.`merge_info`, 1, 1024) AS `merge_info`,
  `profiles`.`merged_from_profile_id` AS `merged_from_profile_id`,
  `users`.`merged_from_user_id` AS `merged_from_user_id`,
  `profiles`.`merged_to_profile_id` AS `merged_to_profile_id`,
  `users`.`merged_to_user_id` AS `merged_to_user_id`,
  `profiles`.`middle_name` AS `middle_name_(profiles)`,
  `registration_audit`.`middle_name` AS `middle_name_(registration_audit)`,
  `membership_applications`.`middle_name` AS `middle_name`,
  `profiles`.`military_id` AS `military_id`,
  `events`.`name` AS `name_(events)`,
  `profiles`.`name` AS `name_(profiles)`,
  `users`.`name` AS `name_(users)`,
  `membership_types`.`name` AS `name`,
  SUBSTRING(`transactions`.`note`, 1, 1024) AS `note`,
  `profiles`.`occupation_id` AS `occupation_id`,
  `users`.`old_email` AS `old_email`,
  `users`.`opted_out_of_notifications` AS `opted_out_of_notifications`,
  `order_products`.`option_amount_per` AS `option_amount_per`,
  SUBSTRING(`order_products`.`options_given`, 1, 1024) AS `options_given`,
  `transactions`.`order_id` AS `order_id_(transactions)`,
  `order_products`.`order_id` AS `order_id`,
  `membership_periods`.`origin` AS `origin`,
  `membership_periods`.`origin_flag` AS `origin_flag_(membership_periods)`,
  `membership_applications`.`origin_flag` AS `origin_flag`,
  `membership_periods`.`origin_status` AS `origin_status`,
  `orders`.`original_tax` AS `original_tax_(orders)`,
  `order_products`.`original_tax` AS `original_tax`,
  `orders`.`original_total` AS `original_total_(orders)`,
  `order_products`.`original_total` AS `original_total`,
  `membership_applications`.`outside_payment` AS `outside_payment`,
  SUBSTRING(`events`.`overview`, 1, 1024) AS `overview`,
  `membership_applications`.`paper_waivers_signed` AS `paper_waivers_signed`,
  `profiles`.`para` AS `para`,
  `users`.`password` AS `password`,
  SUBSTRING(`membership_applications`.`payment_explanation`, 1, 1024) AS `payment_explanation`,
  `transactions`.`payment_id` AS `payment_id_(transactions)`,
  `membership_applications`.`payment_id` AS `payment_id`,
  `transactions`.`payment_method` AS `payment_method`,
  `membership_applications`.`payment_type` AS `payment_type`,
  `members`.`period_status` AS `period_status_(members)`,
  `membership_periods`.`period_status` AS `period_status`,
  SUBSTRING(`users`.`personal_access_token`, 1, 1024) AS `personal_access_token`,
  `orders`.`phone` AS `phone_(orders)`,
  `membership_applications`.`phone` AS `phone`,
  `registration_audit`.`phone_number` AS `phone_number`,
  `membership_applications`.`plan_id` AS `plan_id`,
  `orders`.`post_process_finished_at` AS `post_process_finished_at`,
  `orders`.`post_process_started_at` AS `post_process_started_at`,
  `registration_audit_membership_application`.`price_paid` AS `price_paid`,
  `users`.`primary` AS `primary`,
  `profiles`.`primary_address_id` AS `primary_address_id`,
  `profiles`.`primary_citizenship_id` AS `primary_citizenship_id`,
  `profiles`.`primary_email_id` AS `primary_email_id`,
  `profiles`.`primary_emergency_contact_id` AS `primary_emergency_contact_id`,
  `profiles`.`primary_phone_id` AS `primary_phone_id`,
  `membership_types`.`priority` AS `priority`,
  `transactions`.`processed` AS `processed_(transactions)`,
  `orders`.`processed` AS `processed`,
  `registration_audit`.`processed_at` AS `processed_at_(registration_audit)`,
  `order_products`.`processed_at` AS `processed_at`,
  `order_products`.`product_description` AS `product_description`,
  `order_products`.`product_id` AS `product_id`,
  `registration_audit`.`profile_id` AS `profile_id_(registration_audit)`,
  `membership_applications`.`profile_id` AS `profile_id`,
  `membership_periods`.`progress_status` AS `progress_status`,
  `membership_types`.`published` AS `published`,
  `order_products`.`purchasable_id` AS `purchasable_id`,
  `order_products`.`purchasable_processed_at` AS `purchasable_processed_at`,
  `order_products`.`purchasable_type` AS `purchasable_type`,
  `membership_periods`.`purchased_on` AS `purchased_on`,
  `events`.`qualification_deadline` AS `qualification_deadline`,
  `events`.`qualification_url` AS `qualification_url`,
  `order_products`.`quantity` AS `quantity`,
  `order_products`.`quantity_refunded` AS `quantity_refunded`,
  `orders`.`quote_id` AS `quote_id`,
  `events`.`race_director_id` AS `race_director_id`,
  `registration_audit_membership_application`.`race_id` AS `race_id_(registration_audit_membership_application)`,
  `membership_applications`.`race_id` AS `race_id`,
  `registration_audit_membership_application`.`race_type_id` AS `race_type_id_(registration_audit_membership_application)`,
  `membership_applications`.`race_type_id` AS `race_type_id`,
  `membership_applications`.`referral_code` AS `referral_code`,
  `members`.`referrer_code` AS `referrer_code`,
  `transactions`.`refunded_amount` AS `refunded_amount`,
  `events`.`registration_company_event_id` AS `registration_company_event_id`,
  `registration_audit`.`registration_company_id` AS `registration_company_id`,
  SUBSTRING(`events`.`registration_information`, 1, 1024) AS `registration_information`,
  `events`.`registration_policy_url` AS `registration_policy_url`,
  SUBSTRING(`events`.`registration_url`, 1, 1024) AS `registration_url`,
  `users`.`remember_token` AS `remember_token`,
  `registration_audit`.`remote_audit_code` AS `remote_audit_code`,
  `events`.`remote_id` AS `remote_id_(events)`,
  `membership_periods`.`remote_id` AS `remote_id_(membership_periods)`,
  `profiles`.`remote_id` AS `remote_id_(profiles)`,
  `users`.`remote_id` AS `remote_id_(users)`,
  `registration_audit`.`remote_id` AS `remote_id`,
  `membership_periods`.`renewed_membership_period_id` AS `renewed_membership_period_id`,
  `membership_types`.`require_admin_approval` AS `require_admin_approval`,
  `events`.`sanctioning_event_id` AS `sanctioning_event_id`,
  `orders`.`ship_on` AS `ship_on`,
  `orders`.`shipping_address` AS `shipping_address`,
  `orders`.`shipping_address_2` AS `shipping_address_2`,
  `orders`.`shipping_city` AS `shipping_city`,
  `orders`.`shipping_company` AS `shipping_company`,
  `orders`.`shipping_country` AS `shipping_country`,
  `orders`.`shipping_first_name` AS `shipping_first_name`,
  `orders`.`shipping_last_name` AS `shipping_last_name`,
  `orders`.`shipping_method` AS `shipping_method`,
  `orders`.`shipping_rate` AS `shipping_rate`,
  `orders`.`shipping_state` AS `shipping_state`,
  `orders`.`shipping_tax` AS `shipping_tax`,
  `orders`.`shipping_zip` AS `shipping_zip`,
  SUBSTRING(`membership_types`.`short_description`, 1, 1024) AS `short_description`,
  `order_products`.`sku` AS `sku`,
  `events`.`starts` AS `starts_(events)`,
  `membership_periods`.`starts` AS `starts`,
  `events`.`state` AS `state_(events)`,
  `membership_periods`.`state` AS `state_(membership_periods)`,
  `orders`.`state` AS `state_(orders)`,
  `registration_audit`.`state` AS `state_(registration_audit)`,
  `membership_applications`.`state` AS `state`,
  `events`.`state_code` AS `state_code`,
  `events`.`state_id` AS `state_id`,
  `events`.`state_name` AS `state_name`,
  `events`.`status` AS `status_(events)`,
  `membership_periods`.`status` AS `status_(membership_periods)`,
  `registration_audit`.`status` AS `status_(registration_audit)`,
  `registration_audit_membership_application`.`status` AS `status_(registration_audit_membership_application)`,
  `membership_applications`.`status` AS `status`,
  `orders`.`status_id` AS `status_id_(orders)`,
  `order_products`.`status_id` AS `status_id`,
  `orders`.`store` AS `store`,
  `orders`.`subtotal` AS `subtotal`,
  `profiles`.`suffix` AS `suffix`,
  `membership_types`.`tag_id` AS `tag_id`,
  `orders`.`tax` AS `tax_(orders)`,
  `transactions`.`tax` AS `tax_(transactions)`,
  `order_products`.`tax` AS `tax`,
  SUBSTRING(`order_products`.`tax_info`, 1, 1024) AS `tax_info`,
  SUBSTRING(`transactions`.`tax_transaction`, 1, 1024) AS `tax_transaction`,
  `transactions`.`tax_transaction_code` AS `tax_transaction_code_(transactions)`,
  `orders`.`tax_transaction_code` AS `tax_transaction_code`,
  `membership_periods`.`terminated_on` AS `terminated_on`,
  `order_products`.`title` AS `title`,
  `orders`.`total` AS `total_(orders)`,
  `order_products`.`total` AS `total`,
  `orders`.`tracking` AS `tracking`,
  `order_products`.`tracking_number` AS `tracking_number`,
  `events`.`twitter_url` AS `twitter_url`,
  `orders`.`upcharge` AS `upcharge`,
  `events`.`updated_at` AS `updated_at_(events)`,
  `members`.`updated_at` AS `updated_at_(members)`,
  `membership_periods`.`updated_at` AS `updated_at_(membership_periods)`,
  `membership_types`.`updated_at` AS `updated_at_(membership_types)`,
  `order_products`.`updated_at` AS `updated_at_(order_products)`,
  `orders`.`updated_at` AS `updated_at_(orders)`,
  `profiles`.`updated_at` AS `updated_at_(profiles)`,
  `registration_audit`.`updated_at` AS `updated_at_(registration_audit)`,
  `registration_audit_membership_application`.`updated_at` AS `updated_at_(registration_audit_membership_application)`,
  `transactions`.`updated_at` AS `updated_at_(transactions)`,
  `users`.`updated_at` AS `updated_at_(users)`,
  `membership_applications`.`updated_at` AS `updated_at`,
  SUBSTRING(`membership_applications`.`upgrade_code`, 1, 1024) AS `upgrade_code`,
  SUBSTRING(`registration_audit_membership_application`.`upgrade_codes`, 1, 1024) AS `upgrade_codes`,
  `membership_periods`.`upgraded_from_id` AS `upgraded_from_id`,
  `membership_periods`.`upgraded_to_id` AS `upgraded_to_id`,
  `profiles`.`user_id` AS `user_id_(profiles)`,
  `registration_audit`.`user_id` AS `user_id_(registration_audit)`,
  `transactions`.`user_id` AS `user_id_(transactions)`,
  `orders`.`user_id` AS `user_id`,
  `users`.`username` AS `username`,
  `orders`.`uuid` AS `uuid_(orders)`,
  `profiles`.`uuid` AS `uuid_(profiles)`,
  `users`.`uuid` AS `uuid_(users)`,
  `membership_applications`.`uuid` AS `uuid`,
  `events`.`virtual` AS `virtual`,
  `membership_periods`.`waiver_status` AS `waiver_status`,
  `events`.`youtube_url` AS `youtube_url`,
  `events`.`zip` AS `zip_(events)`,
  `orders`.`zip` AS `zip_(orders)`,
  `registration_audit`.`zip` AS `zip_(registration_audit)`,
  `membership_applications`.`zip` AS `zip`
  
FROM `membership_applications`
  LEFT JOIN `order_products` ON (`membership_applications`.`id` = `order_products`.`purchasable_id`)
  LEFT JOIN `orders` ON (`order_products`.`order_id` = `orders`.`id`)
  LEFT JOIN `registration_audit` ON (`membership_applications`.`membership_period_id` = `registration_audit`.`membership_period_id`)
  LEFT JOIN `registration_audit_membership_application` ON (`registration_audit`.`id` = `registration_audit_membership_application`.`audit_id`)
  RIGHT JOIN `membership_periods` ON (`membership_applications`.`membership_period_id` = `membership_periods`.`id`)
  LEFT JOIN `membership_types` ON (`membership_applications`.`membership_type_id` = `membership_types`.`id`)
  RIGHT JOIN `members` ON (`membership_periods`.`member_id` = `members`.`id`)
  RIGHT JOIN `profiles` ON (`members`.`memberable_id` = `profiles`.`id`)
  LEFT JOIN `users` ON (`profiles`.`user_id` = `users`.`id`)
  LEFT JOIN `events` ON (`membership_applications`.`event_id` = `events`.`id`)
  LEFT JOIN `transactions` ON (`orders`.`id` = `transactions`.`order_id`)
  
WHERE
	membership_periods.membership_type_id NOT IN (56, 58, 81, 105)
	AND
	membership_periods.id NOT IN (4652554)
  AND
  membership_periods.ends >= 2022-01-01
LIMIT 100;

